---
all:
  vars:
    install_rke2_version: "v1.27.10+rke2r1"
    #install_rke2_version: "v1.22.0+rke2r1"
    ansible_user: root

rke2_cluster:
  children:
    rke2_servers:
      hosts:
        master3:
          ansible_host: 10.10.25.164
          #rke2_role: server #prob dont need....already built-into site.yaml
    rke2_agents:
      hosts:
        worker3:
          ansible_host: 10.10.25.165
          #rke2_role: agent #prob dont need....already built-into site.yaml
    dns_servers:
      hosts:
        localhost:
          ansible_connection: local
          ansible_host: 10.10.25.163

