---
- name: Create the /etc/rancher/rke2 config dir
  ansible.builtin.file:
    path: /etc/rancher/rke2
    state: directory
    recurse: yes

- name: Add pod security admission config file
  vars:
    file_contents: "{{ lookup('file', pod_security_admission_config_file_path) }}"
  ansible.builtin.template:
    src: ansible_header.j2
    dest: "/etc/rancher/rke2/pod-security-admission-config.yaml"
    mode: '0640'
    owner: root
    group: root
  when:
    - pod_security_admission_config_file_path is defined
    - pod_security_admission_config_file_path|length != 0
  notify: Restart rke2-server

- name: Remove pod security admission config file
  when:
    - pod_security_admission_config_file_path is not defined or pod_security_admission_config_file_path|length == 0
  block:
    - name: Check that the PSA config file exists
      ansible.builtin.stat:
        path: "/etc/rancher/rke2/pod-security-admission-config.yaml"
      register: stat_result

    - name: "Check that the PSA config file has ansible managed comments"
      ansible.builtin.lineinfile:
        name: "/etc/rancher/rke2/pod-security-admission-config.yaml"
        line: '## This is an Ansible managed file, contents will be overwritten ##'
        state: present
      check_mode: yes
      register: ansible_managed_check
      when: stat_result.stat.exists | bool is true

    - name: Remove the PSA config file if exists and has ansible managed comments
      ansible.builtin.file:
        path: "/etc/rancher/rke2/pod-security-admission-config.yaml"
        state: absent
      when:
        - ansible_managed_check.changed | bool is false
