---
- name: Configure DNS with dnsmasq
  hosts: all
  become: true
  roles:
    - role: dnsmasq
      tags: dns
  vars_prompt:
    - name: ansible_become_password
      prompt: "Enter sudo password"
      private: yes

- name: Updates and Docker Setup
  hosts: rke2_servers,rke2_agents
  become: true
  roles:
    - role: common
      tags: common
    - role: docker
      tags: docker 

- name: Server play
  hosts: rke2_servers
  any_errors_fatal: true
  become: true
  roles:
    - role: rke2_server
  serial: 5

- name: Agent play
  hosts: rke2_agents
  any_errors_fatal: true
  become: true
  roles:
    - role: rke2_agent
  serial: 10

- name: Cluster manifest play
  hosts: rke2_servers
  any_errors_fatal: true
  become: true
  roles:
    - role: cluster_manifest
